<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>局域网搬家</AssemblyName>
    <RootNamespace>LanDrop</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.2.3</Version>
    <AssemblyVersion>2.2.3.0</AssemblyVersion>
    <FileVersion>2.2.3.0</FileVersion>
    <InformationalVersion>2.2.3</InformationalVersion>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
